# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:14.18

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Installing Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Generating .env
          command: chmod +x build/create_env_vars.sh; ./build/create_env_vars.sh; cd build; ls -al

      - run: 
          name: Building
          command: npm run build

      - run:
          name: Upload Build
          command: scp -o "StrictHostKeyChecking no" /home/circleci/repo/dist/bundle.js circleci@seanpowell.dev:/var/www/api/income-tracker.js

      - run:
          name: Starting Server
          command: ssh -o "StrictHostKeyChecking no" circleci@seanpowell.dev "cd /var/www/api; pm2 delete income-tracker; pm2 start income-tracker.js"
